// <auto-generated />
using System;
using HvZWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HvZWebAPI.Migrations
{
    [DbContext(typeof(HvZDbContext))]
    [Migration("20221004100008_Add_Data")]
    partial class Add_Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HvZWebAPI.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ChatTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHumanGlobal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsZombieGlobal")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatTime = new DateTime(2022, 10, 4, 12, 0, 8, 394, DateTimeKind.Local).AddTicks(6495),
                            GameId = 2,
                            IsHumanGlobal = false,
                            IsZombieGlobal = true,
                            Message = "Got him!",
                            PlayerId = 2
                        },
                        new
                        {
                            Id = 2,
                            ChatTime = new DateTime(2022, 10, 4, 12, 0, 8, 394, DateTimeKind.Local).AddTicks(6505),
                            GameId = 2,
                            IsHumanGlobal = true,
                            IsZombieGlobal = false,
                            Message = "Run away!",
                            PlayerId = 1
                        },
                        new
                        {
                            Id = 3,
                            ChatTime = new DateTime(2022, 10, 4, 12, 0, 8, 394, DateTimeKind.Local).AddTicks(6512),
                            GameId = 2,
                            IsHumanGlobal = false,
                            IsZombieGlobal = false,
                            Message = "Like... Hello",
                            PlayerId = 3
                        });
                });

            modelBuilder.Entity("HvZWebAPI.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jungle",
                            State = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Island",
                            State = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ocean",
                            State = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Space",
                            State = 2
                        });
                });

            modelBuilder.Entity("HvZWebAPI.Models.Kill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("KillerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeDeath")
                        .HasColumnType("datetime2");

                    b.Property<int>("VictimId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("KillerId");

                    b.HasIndex("VictimId");

                    b.ToTable("Kills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 2,
                            KillerId = 2,
                            TimeDeath = new DateTime(2022, 10, 4, 12, 0, 8, 394, DateTimeKind.Local).AddTicks(6375),
                            VictimId = 1
                        },
                        new
                        {
                            Id = 2,
                            GameId = 2,
                            KillerId = 4,
                            TimeDeath = new DateTime(2022, 10, 4, 12, 0, 8, 394, DateTimeKind.Local).AddTicks(6437),
                            VictimId = 3
                        },
                        new
                        {
                            Id = 3,
                            GameId = 2,
                            KillerId = 2,
                            TimeDeath = new DateTime(2022, 10, 4, 12, 0, 8, 394, DateTimeKind.Local).AddTicks(6442),
                            VictimId = 4
                        });
                });

            modelBuilder.Entity("HvZWebAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BiteCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHuman")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPatientZero")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BiteCode = "Street",
                            GameId = 2,
                            IsHuman = true,
                            IsPatientZero = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BiteCode = "BooHoo",
                            GameId = 2,
                            IsHuman = false,
                            IsPatientZero = true,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            BiteCode = "Hello",
                            GameId = 2,
                            IsHuman = false,
                            IsPatientZero = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            BiteCode = "Hello",
                            GameId = 2,
                            IsHuman = true,
                            IsPatientZero = false,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("HvZWebAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ole",
                            LastName = "Streetman"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Eivind",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Ibrahim",
                            LastName = "Banjai"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Hakon",
                            LastName = "Haga"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Patricia",
                            LastName = "Mahomes"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "James",
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Lamar",
                            LastName = "Random"
                        });
                });

            modelBuilder.Entity("HvZWebAPI.Models.Chat", b =>
                {
                    b.HasOne("HvZWebAPI.Models.Game", "Game")
                        .WithMany("Chats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HvZWebAPI.Models.Player", "Player")
                        .WithMany("Chats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HvZWebAPI.Models.Kill", b =>
                {
                    b.HasOne("HvZWebAPI.Models.Game", "Game")
                        .WithMany("Kills")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HvZWebAPI.Models.Player", "Killer")
                        .WithMany("Kills")
                        .HasForeignKey("KillerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HvZWebAPI.Models.Player", "Victim")
                        .WithMany("Deaths")
                        .HasForeignKey("VictimId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Killer");

                    b.Navigation("Victim");
                });

            modelBuilder.Entity("HvZWebAPI.Models.Player", b =>
                {
                    b.HasOne("HvZWebAPI.Models.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HvZWebAPI.Models.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HvZWebAPI.Models.Game", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Kills");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("HvZWebAPI.Models.Player", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Deaths");

                    b.Navigation("Kills");
                });

            modelBuilder.Entity("HvZWebAPI.Models.User", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
